## Project Description


In [5]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd

## load the dataset
data=gutenberg.raw("shakespeare-hamlet.txt")

[nltk_data] Downloading package gutenberg to C:\Users\Rayan
[nltk_data]     Ahmed.R/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [6]:
with open('hamlet.txt','w') as file:
    file.write(data)

In [8]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [7]:
## Data Preprocessing
import numpy as np
import tensorflow 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences   
from sklearn.model_selection import train_test_split
with open('hamlet.txt','r') as file:
    text=file.read().lower()

# Tokenize the text
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1


In [8]:
## Data Preprocessing
import numpy as np
import tensorflow 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences   
from sklearn.model_selection import train_test_split
with open('hamlet.txt','r') as file:
    text=file.read().lower()

# Tokenize the text
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1


In [9]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [10]:
import numpy as np
import tensorflow as tf
import sklearn

print(np.__version__)
print(tf.__version__)
print(sklearn.__version__)


1.25.2
2.15.0
1.7.1


In [11]:
## create input sequences
inputsequences=[]
for line in text.split('.'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        inputsequences.append(n_gram_sequence)
        

In [12]:
inputsequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1, 687, 4, 45, 41, 1886, 1887, 1888, 1180],
 [1, 687, 4, 45, 41, 1886, 1887, 1888, 1180, 1889],
 [1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [1182, 63],
 [1182, 63, 408],
 [162, 377],
 [162, 377, 21],
 [162, 377, 21, 247],
 [162, 377, 21, 247, 882],
 [162, 377, 21, 247, 882, 18],
 [162, 377, 21, 247, 882, 18, 66],
 [162, 377, 21, 247, 882, 18, 66, 451],
 [224, 248],
 [224, 248, 1],
 [224, 248, 1, 30],
 [224, 248, 1, 30, 408],
 [407, 451],
 [25, 408],
 [6, 43],
 [6, 43, 62],
 [6, 43, 62, 1893],
 [6, 43, 62, 1893, 96],
 [6, 43, 62, 1893, 96, 18],
 [6, 43, 62, 1893, 96, 18, 566],
 [6, 43, 62, 1893, 96, 18, 566, 451],
 [71, 51],
 [71, 51, 1894],
 [71, 51, 1894, 567],
 [71, 51, 1894, 567, 378],
 [71, 51, 1894, 567, 378, 80],
 [71, 51, 1894, 567, 378

In [13]:
## Pad sequences
max_sequence_len=max([len(x) for x in inputsequences])
max_sequence_len

162

In [14]:
input_sequences=np.array(pad_sequences(inputsequences,maxlen=max_sequence_len,padding='pre'))


In [15]:
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [16]:
## Create predictors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]
y



array([ 687,    4,   45, ..., 1047,    4,  193])

In [17]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)

In [18]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
#Lstm and RNN model
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional,Dropout

model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 161, 100)          481800    
                                                                 
 lstm (LSTM)                 (None, 161, 150)          150600    
                                                                 
 dropout (Dropout)           (None, 161, 150)          0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 4818)              486618    
                                                                 
Total params: 1219418 (4.65 MB)
Trainable params: 1219418 (4.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
#train the model
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1)


Epoch 1/50


696/696 [==============================] - 132s 184ms/step - loss: 6.8557 - accuracy: 0.0325 - val_loss: 6.7410 - val_accuracy: 0.0370
Epoch 2/50
696/696 [==============================] - 110s 158ms/step - loss: 6.4430 - accuracy: 0.0366 - val_loss: 6.8426 - val_accuracy: 0.0440
Epoch 3/50
696/696 [==============================] - 107s 154ms/step - loss: 6.2962 - accuracy: 0.0463 - val_loss: 6.8678 - val_accuracy: 0.0563
Epoch 4/50
696/696 [==============================] - 126s 180ms/step - loss: 6.1275 - accuracy: 0.0532 - val_loss: 6.8719 - val_accuracy: 0.0588
Epoch 5/50
696/696 [==============================] - 128s 184ms/step - loss: 5.9718 - accuracy: 0.0593 - val_loss: 6.9547 - val_accuracy: 0.0644
Epoch 6/50
696/696 [==============================] - 269s 386ms/step - loss: 5.8245 - accuracy: 0.0672 - val_loss: 7.0076 - val_accuracy: 0.0626
Epoch 7/50
696/696 [==============================] - 264s 379ms/step - loss: 5.6626 - accuracy: 0.0745 - val_loss: 7.0544

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [22]:
model.save("my_model.h5")


c:\anaconda3\envs\tf_env\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [2]:
def predict_next_word(model,tokenizer,text,max_sequence_len):
    token_list=tokenizer.texts_to_sequences([text])[0]
    token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
    predicted=model.predict(token_list,verbose=0)
    predicted_word_index=np.argmax(predicted,axis=1)[0]
    
    for word,index in tokenizer.word_index.items():
        if index==predicted_word_index:
            return word
    return None

In [26]:
input_text="To be or not to be"
print(f"Input text: {input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next word: {next_word}")

Input text: To be or not to be
Next word: though


In [27]:
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [34]:
input_text="not my"
print(f"Input text: {input_text}")
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)    
print(f"Next word: {next_word}")

Input text: not my
Next word: lord


In [2]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [36]:
import tensorflow as tf
import keras

In [15]:
which python  # Linux/Mac
where python  # Windows


SyntaxError: invalid syntax (1698765103.py, line 1)